CREATE DATABASE IF NOT EXISTS quiz_data;
USE quiz_data;

CREATE TABLE IF NOT EXISTS questions (
    id INT AUTO_INCREMENT PRIMARY KEY,
    topic VARCHAR(255) NOT NULL,
    questions TEXT NOT NULL,
    A VARCHAR(255) NOT NULL,
    B VARCHAR(255) NOT NULL,
    C VARCHAR(255) NOT NULL,
    D VARCHAR(255) NOT NULL,
    answer VARCHAR(1) NOT NULL
);
